services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy
    environment:
      - LANG=en
      - WG_HOST=${IP}
      - PORT=51821
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.0.x
      - INIT_DNS=10.8.0.1
      - WG_PERSISTENT_KEEPALIVE=25
      - WEBROOT_BIND_ADDRESS=127.0.0.1
      - WG_ALLOWED_IPS=0.0.0.0/0
      - EXPERIMENTAL_AWG=true
      - OVERRIDE_AUTO_AWG=awg
      - INSECURE=true
      - WG_DEVICE=eth0
      - INIT_ENABLED=true
      - INIT_USERNAME=${ADMIN_USER}
      - INIT_PASSWORD=${ADMIN_PASSWORD}
      - WG_POST_UP=iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT
      - WG_POST_DOWN=iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE; iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT
      - INIT_HOST=${IP}
      - INIT_PORT=51820
    volumes:
      - ./wg-easy-data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    network_mode: "host"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    healthcheck:
      test: ["CMD", "awg", "show", "wg0"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  adguardhome:
    image: adguard/adguardhome:v0.107.79
    container_name: adguardhome
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./adguard-data:/opt/adguardhome/work
      - ./adguard-conf:/opt/adguardhome/conf
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      wg-easy:
        condition: service_healthy
      adguard-init:
        condition: service_completed_successfully
  
  nginx:
    image: nginx:stable
    container_name: nginx
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    deploy:
      resources:
        limits:
          memory: 1G
    depends_on:
      wg-easy:
        condition: service_healthy
      adguardhome:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  adguard-init:
    image: alpine:latest
    container_name: adguard-init
    volumes:
      - ./adguard-conf:/config
    env_file:
      - .env
    entrypoint: 
      - /bin/sh
      - -c
      - |
        apk add --no-cache apache2-utils gettext
        export ADGUARD_PASSWORD_HASH=$$(htpasswd -B -n -b "$$ADMIN_USER" "$$ADMIN_PASSWORD" | cut -d ":" -f 2)
        envsubst < /config/AdGuardHome.yaml.template > /config/AdGuardHome.yaml